---
- hosts: 172.31.8.226
  become: yes
  tasks:
  - name: i want execute direct linux command
    command: hostname -f
    register: myfirsttaskresult


  - name: install git
    apt:
     name: git
     state: present
    when: myfirsttaskresult.stderr ==""

  - name: install wget
    apt:
     name: wget
     state: present
    when: myfirsttaskresult.stderr !=""
    