---
- hosts: 172.31.8.226
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
     name: apache2
     state: present
   
  - name: i want to copy indexfile into node side
    ansible.builtin.template:
       src: vijay.j2
       dest: /var/www/html/index.html
    notify:
      - restartwebserver

  - name: Download remote files
    get_url:
     url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
     dest: /home/ubuntu/jenkins.war
     force_basic_auth: yes

  - name: i want to Create directory
    file:
     path: /home/ubuntu/myfolder2
     state: directory

  handlers:
  - name: restartwebserver
    debug:
         msg: "{{ansible_os_family}}"